parameters:
#    nlsnlsdb.example.class: nls\Bundle\nlsdbBundle\Example

services:
#    nlsnlsdb.example:
#        class: %nlsnlsdb.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
